### ISSUE TITLE
when google update class name

### ISSUE THREAD

**Issue by saselovejulie** [zlurad/serp-parser#62]
in this project we use lots of Class name in selector.
but as i know google will update those class name with no regular.
those six char random class see not stable enough.
is there any good solution to avoid the effect when google update class name?

**Comment by badluck13** [comment]
There is a way to use the :nth selectors but it's also not stable as there is no way to get it future proof. As far as we have data, google is not updating classes soo often, we only saw one major change in 2 years.

**Comment by cnscorpions** [comment]
CSS class name is generated by javascript, and it's a challenge for web scraping. 😂
