### ISSUE TITLE
example for use es5 with request lib not work 

### ISSUE THREAD

**Issue by cnscorpions** [zlurad/serp-parser#63]
environment:
OS: Ubuntu 18.04
node: v12.18.3

source code:
```
var request = require("request")
var sp = require("serp-parser")

request('https://www.google.com/search?q=hello', function (error, response, html) {
  if (!error && response.statusCode == 200) {
    console.log(sp.GoogleSERP(html));
  }
});
```

output:
```
{
  currentPage: 1,
  keyword: '',
  organic: [],
  pagination: [],
  relatedKeywords: []
}
```

It's not convenient for me to query google from China.

Please help to work it out.

Thank you, guys

**Comment by badluck13** [comment]
Hi @cnscorpions we are working on the fix and we will have it up and running soon. Google did a full redesign of their no-js result pages and we need to transition to it. Will update here when we are done with transition

**Comment by cnscorpions** [comment]
all right, close it.
