### ISSUE TITLE
Empty Organic Results at tag 0.4.1

### ISSUE THREAD

**Issue by marcelinhov2** [zlurad/serp-parser#64]
Hey guys, I was using this package  to parse results from my google scrapper but I'm not getting my organic results parsed anymore. Does anyone else is having this problem?

Thanks.

**Comment by badluck13** [comment]
We are working on the fix, Google did one more update to move to Material and change the structure a bit. We'll have one working shortly

**Comment by marcelinhov2** [comment]
Thanks for the feedback 👍

**Comment by marcelinhov2** [comment]
Hey @badluck13, how are you doing? Any update about the issue?

Thanks.

**Comment by badluck13** [comment]
Hi, @marcelinhov2 we just started working on it, and it will be done tomorrow. It's a lot to process and we want to keep coverage and testing on the same level as in previous versions

**Comment by marcelinhov2** [comment]
Thank you very much @badluck13 👍

**Comment by marcelinhov2** [comment]
Hey @badluck13, how are you? Any update? Can I help with something?

Thanks 🤘

**Comment by badluck13** [comment]
HI, @marcelinhov2 please use the latest beta version: 0.5.0-beta.0 of the parser, it should work with organic for now. We are working on splitting the code for desktop and no-js parsers, and we are in transition to a new design. It will take some time, but for now, it should work for organics on the full google search results page.

**Comment by marcelinhov2** [comment]
Hey, @badluck13 I tried to use the tag but got this problem:

![image](https://user-images.githubusercontent.com/232648/95752369-4ba96900-0c76-11eb-8078-50aa384fab8d.png)

**Comment by badluck13** [comment]
Sorry to hear that. Can you make a small demo with your data so we can debug

**Comment by marcelinhov2** [comment]
Sure, here it is: https://codepen.io/marcelinhov2/pen/QWEbeGe

**Comment by badluck13** [comment]
Hm, it works on my end. 

Can you try this on your js, put that page in test.html next to it:

```
const sp = require("serp-parser");
const fs = require("fs");

html = fs.readFileSync('test.html', { encoding: 'utf8' });
parser = new sp.GoogleSERP(html);

console.dir(parser.serp);
```

**Comment by badluck13** [comment]
Here is it on the `codesandbox` https://codesandbox.io/s/thirsty-architecture-fnyii?file=/src/index.js

See result in the console: https://fnyii.csb.app/

**Comment by marcelinhov2** [comment]
Ok it worked now, but the use have changed. That's why it didn't work the first time. 

Thanks man.
