### ISSUE TITLE
RelatedKeywords returning always an empty array

### ISSUE THREAD

**Issue by marcelinhov2** [zlurad/serp-parser#72]
Hey everyone, how are you?

One of my current flows need the related keywords from google response page. Sometime ago, I'm pretty sure it was working but now I'm always getting an empty array.

Thanks.

**Comment by Gozza** [comment]
Hi @marcelinhov2,

It seems like Google again did some update, I'm working on it. It should be done at some time today.

**Comment by marcelinhov2** [comment]
Thank you so much @Gozza.

**Comment by marcelinhov2** [comment]
Any update @Gozza? Please let me know if I can help with anything.

Thanks.

**Comment by badluck13** [comment]
Hi, @marcelinhov2 this is fixed in version 1.2.1 it's available on npm

@Gozza did it timely I was just late with publishing, let us know if there is anything more you find and you are more than welcome to help with code :)

**Comment by marcelinhov2** [comment]
It's working. Thanks for the fix and for the good work @badluck13 @Gozza.

**Comment by badluck13** [comment]
@marcelinhov2 hey I just wanted to reach out as we published new version where you can specify if you want only some features to parse, and I remembered you mentioning you use related keywords, so you can parse only them with this code:

```
const options = {
  related: true
}
const parser = new GoogleSERP(html, options);
```
