### ISSUE TITLE
Ads Snippets are empty

### ISSUE THREAD

**Issue by marcelinhov2** [zlurad/serp-parser#91]
Hey guys, 

I just check that the snippets are returning empty for the adwords section. 

<img width="599" alt="image" src="https://user-images.githubusercontent.com/232648/129787590-b3fc7922-6944-44d7-887d-21b272eae170.png">

Can you guys take a look?

Thank you so much.

**Comment by marcelinhov2** [comment]
Hi team, hope you are all safe and well. 

Do you think this makes sense? Please let me know.

Thank you :)

**Comment by badluck13** [comment]
Hi, @marcelinhov2 sorry vacation season is taking a toll :) 
I'll check it out this weekend

**Comment by marcelinhov2** [comment]
Sorry to bother you @badluck13. Thank you so much for your reply, I hope you enjoyed your vacation. 🙏

**Comment by marcelinhov2** [comment]
nothing yet? thanks.

**Comment by badluck13** [comment]
Hi, @marcelinhov2 we have an issue tracking this one down as we get the data back with all the pages we tried, now I'm under the impression they are a/b testing the ads for different target markets. Can you share with us, the link of the google page as an example so we can test it with our parser and see what's wrong? Thanks!
