### ISSUE TITLE
Update Parsing Desktop SERP result pages for latest Google update

### ISSUE THREAD

**Issue by marcelinhov2** [zlurad/serp-parser#93]
Hey team, nice to speak with you again.

The parser is very unstable, it's not returning videos anymore, ads, images... Do you have any plan for updates?

Thanks.

**Comment by badluck13** [comment]
Hi, @marcelinhov2 I'm on it today, working on a tester project to report issues as they happen as well. Hopefully we got something in next 3-4h

Thanks for holding out for us!

**Comment by badluck13** [comment]
![image](https://user-images.githubusercontent.com/186824/141471426-a02417f7-e544-4777-b903-e9672c7ad79a.png)
Yeah there are some issues :)

**Comment by marcelinhov2** [comment]
you are the best @badluck13. Thank you :)

**Comment by badluck13** [comment]
@marcelinhov2 this is done for the Desktop version of Google SERP, I still need to go over no-js and mobile versions to check the changes there as well. Let me know if something breaks again :)
